backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
  - label: "Digital Bets"
    name: "digital_bets"
    editor:
      preview: false
    files:
      - label: "Product Teams"
        name: "product_teams"
        file: "content/digital_bets.json"
        fields:
          - label: Projects
            name: projects
            widget: list
            fields:
              - {label: "Project Name", name: "project_name", widget: "string"}
              - {
                  label: "Temporality",
                  name: "temporality",
                  widget: "select",
                  options: ["Now", "Next", "Future", "On-hold", "Canceled"],
                  default: ["Now"],
                }
              - {
                  label: "Phase",
                  name: "phase",
                  widget: "select",
                  options:
                    [
                      "Ideation",
                      "Discovery",
                      "Validation",
                      "Confirmation",
                      "Transfer",
                      "Launch",
                      "Sustaining innovation",
                      "Efficiency",
                      "Mature business",
                      "Declining business",
                      "Renovation",
                    ],
                  default: ["Discovery"],
                }
              - {label: "Big bet", name: "big_bet", widget: boolean, default: true}
              - {label: "Product team", name: "product_team", widget: string}
              - {label: "Effort", name: "effort", widget: number, value_type: "float"}
              - {label: "Type of project", name: "project_type", widget: string}
              - {
                  label: "Project stakeholder",
                  name: "project_stakeholder",
                  widget: string,
                }
  - label: "Focus Areas"
    name: "focus_areas"
    editor:
      preview: false
    files:
      - label: "Focus Areas"
        name: "focus_areas"
        file: "content/focus_areas.json"
        fields:
          - label: Focus Areas
            name: focus_areas
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string"}
  - label: "Events"
    name: "events"
    editor:
      preview: false
    files:
      - label: "Upcoming innovations events"
        name: "events"
        file: "content/events.json"
        fields:
          - label: Events
            name: events
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "desc", widget: "string"}
              - {
                  label: "Source",
                  name: "tag",
                  widget: "select",
                  options: ["Internal", "External"],
                  default: ["Internal"],
                }
              - {
                  label: "Date",
                  name: "date",
                  widget: "datetime",
                  default: "",
                  date_format: "DD.MM.YYYY",
                  time_format: false,
                  picker_utc: true,
                }
  - label: "Overview Panel"
    name: "overviewPanel"
    editor:
      preview: false
    files:
      - label: "Overview panel"
        name: "overviewPanel"
        file: "content/overviewPanel.json"
        fields:
          - label: "Innovation investments"
            name: "innovationInvestments"
            widget: list
            max: 5
            min: 1
            fields:
              - {label: "Chart label", name: label, widget: string, default: ""}
              - {label: "ID", name: id, widget: string, default: ""}
              - {label: "Chart value", name: value, widget: number, default: 0}
          - label: "How much do we do?"
            name: "progressData"
            widget: "object"
            fields:
              - {
                  label: Innovation rate in total turnover,
                  name: innovationRate,
                  widget: number,
                  default: 0,
                }
              - label: "Progress bars"
                name: "progressBars"
                widget: list
                max: 3
                min: 1
                fields:
                  - {
                      label: "Progress bar label",
                      name: label,
                      widget: string,
                      default: "",
                    }
                  - {
                      label: "Progress bar percentage",
                      name: value,
                      widget: number,
                      default: 0,
                    }
          - label: "Top recycling trends"
            name: "recyclingTrends"
            widget: list
            max: 3
            min: 1
            fields:
              - {label: "Trend label", name: label, widget: string, default: ""}
  - label: "Shortcut Image"
    name: "shortcut_image"
    editor:
      preview: true
    files:
      - label: "Shortcut Image"
        name: "shortcutImage"
        file: "content/shortcutImage.json"
        widget: "object"
        fields:
          - {
              label: "Shortcut Image",
              name: shortcut_image,
              widget: image,
              choose_url: true,
              default: "/images/uploads/shortcut_image.jpg",
              media_library: {config: {multiple: false}},
            }
