backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
  - label: "Products"
    name: "products"
    editor:
      preview: false
    files:
      - label: "Products"
        name: "products"
        file: "content/products.json"
        fields:
          - label: Products
            name: products
            widget: list
            fields:
              - {label: "Product name", name: "title", widget: string}
              - {
                  label: "Phase",
                  name: "phase",
                  widget: "select",
                  options: ["Future", "Next", "0%", "50%", "100%", "Launched product"],
                  default: ["Future"],
                }
              - {
                  label: "Financial effort",
                  name: "effort",
                  widget: number,
                  value_type: "float",
                }
              - {label: "Big bet", name: "big_bet", widget: boolean, default: false}
              - {label: "Feature", name: "feature", widget: boolean, default: false}
              - {
                  label: "Status",
                  name: "status",
                  widget: "select",
                  options: ["Ongoing", "Paused", "Cancelled"],
                  default: ["Ongoing"],
                }
              - {
                  label: "Resume date",
                  name: "date_resume",
                  widget: "datetime",
                  default: "",
                  date_format: "DD.MM.YYYY",
                  time_format: false,
                  picker_utc: true,
                  required: false,
                }
              - {
                  label: "Added date",
                  name: "date_added",
                  widget: "datetime",
                  default: "now",
                  date_format: "DD.MM.YYYY",
                  time_format: false,
                  picker_utc: true,
                }
  - label: "Ideas"
    name: "ideas"
    editor:
      preview: false
    files:
      - label: "Ideas"
        name: "ideas"
        file: "content/ideas.json"
        fields:
          - label: Ideas
            name: ideas
            widget: list
            fields:
              - {label: "Idea", name: "title", widget: string}
              - {
                  label: "Phase",
                  name: "phase",
                  widget: "select",
                  options:
                    [
                      "New ideas",
                      "Test",
                      "Deep test",
                      "Dragons den",
                      "Transfer to product",
                    ],
                  default: ["New ideas"],
                }
              - {
                  label: "Financial effort",
                  name: "effort",
                  widget: number,
                  value_type: "float",
                }
              - {
                  label: "Status",
                  name: "status",
                  widget: "select",
                  options: ["Ongoing", "Paused", "Cancelled"],
                  default: ["Ongoing"],
                }
              - {label: "Big bet", name: "big_bet", widget: boolean, default: false}
              - {
                  label: "Resume date",
                  name: "date_resume",
                  widget: "datetime",
                  default: "",
                  date_format: "DD.MM.YYYY",
                  time_format: false,
                  picker_utc: true,
                  required: false,
                }
              - {
                  label: "Added date",
                  name: "date_added",
                  widget: "datetime",
                  default: "now",
                  date_format: "DD.MM.YYYY",
                  time_format: false,
                  picker_utc: true,
                }
  - label: "Events"
    name: "events"
    editor:
      preview: false
    files:
      - label: "Upcoming innovations events"
        name: "events"
        file: "content/events.json"
        fields:
          - label: Events
            name: events
            widget: list
            fields:
              - {label: "Title", name: "title", widget: string}
              - {label: "Description", name: "desc", widget: string}
              - {
                  label: "Source",
                  name: "tag",
                  widget: "select",
                  options: ["Internal", "External"],
                  default: ["Internal"],
                }
              - {
                  label: "Date",
                  name: "date",
                  widget: "datetime",
                  default: "",
                  date_format: "DD.MM.YYYY",
                  time_format: false,
                  picker_utc: true,
                }
  - label: "Current focus"
    name: "currentFocus"
    editor:
      preview: false
    files:
      - label: "Current focus"
        name: "currentFocus"
        file: "content/currentFocus.json"
        fields:
          - label: Current focus
            name: currentFocus
            widget: list
            fields:
              - {label: "Focus area name", name: "label", widget: string}
              - {label: "Importance", name: "value", widget: number, default: 0}
  - label: "Overview Panel"
    name: "overviewPanel"
    editor:
      preview: false
    files:
      - label: "Overview panel"
        name: "overviewPanel"
        file: "content/overviewPanel.json"
        fields:
          - label: "Ideas"
            name: "overviewIdeas"
            widget: "object"
            fields:
              - {label: Response time, name: responseTime, widget: number, default: 0}
              - {
                  label: Response time T-1,
                  name: responseTimeT1,
                  widget: number,
                  default: 0,
                  required: false,
                }
              - {
                  label: Average evaluation time,
                  name: evaluationTime,
                  widget: number,
                  default: 0,
                }
          - label: "Products"
            name: "overviewProducts"
            widget: "object"
            fields:
              - {label: Lead time, name: leadTime, widget: number, default: 0}
              - {
                  label: Lead time T-1,
                  name: leadTimeT1,
                  widget: number,
                  default: 0,
                  required: false,
                }
              - {label: Number of learnings, name: learnings, widget: number, default: 0}
              - {
                  label: Number of learnings T-1,
                  name: learningsT1,
                  widget: number,
                  default: 0,
                  required: false,
                }
          - label: "Transformation investments"
            name: "transformationInvestments"
            widget: list
            max: 5
            min: 1
            fields:
              - {label: "Chart label", name: label, widget: string, default: ""}
              - {label: "ID", name: id, widget: string, default: ""}
              - {label: "Chart value", name: value, widget: number, default: 0}
          - label: "How much do we do?"
            name: "progressData"
            widget: "object"
            fields:
              - {
                  label: Innovation rate in total turnover,
                  name: innovationRate,
                  widget: number,
                  default: 0,
                }
              - label: "Progress bars"
                name: "progressBars"
                widget: list
                max: 3
                min: 1
                fields:
                  - {
                      label: "Progress bar label",
                      name: label,
                      widget: string,
                      default: "",
                    }
                  - {
                      label: "Progress bar percentage",
                      name: value,
                      widget: number,
                      default: 0,
                    }
          - label: "Top recycling trends"
            name: "recyclingTrends"
            widget: list
            max: 3
            min: 1
            fields:
              - {label: "Trend label", name: label, widget: string, default: ""}
  - label: "Shortcut Image"
    name: "shortcut_image"
    editor:
      preview: true
    files:
      - label: "Shortcut Image"
        name: "shortcutImage"
        file: "content/shortcutImage.json"
        widget: "object"
        fields:
          - {
              label: "Shortcut Image",
              name: shortcut_image,
              widget: image,
              choose_url: true,
              default: "/images/uploads/shortcut_image.jpg",
              media_library: {config: {multiple: false}},
            }
